baseURL = 'https://jorisar.github.io/portfolio'
languageCode = 'en-us'
title = 'Joris Rijsdijk'
theme = "ananke"


[params]
  github = "https://github.com/JorisAR"
  youtube = "https://www.youtube.com/@thecodejar"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/banner.png"
  favicon = "favicon.ico"
  site_logo = "/portfolio/images/global/jar_white_no_background_transparent.png"

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 2

[[menu.main]]
  name = "Projects"
  url = "/posts/"
  weight = 3

[taxonomies]
  tag = "tags"
