baseURL = 'https://jorisar.github.io/portfolio'
languageCode = 'en-us'
title = 'Portfolio'
theme = "ananke"


[params]
  description = "The last theme you'll ever need. Maybe."
  github = "https://github.com/JorisAR"
  youtube = "https://www.youtube.com/@thecodejar"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/banner.png"

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 2

[[menu.main]]
  name = "Projects"
  url = "/posts/"
  weight = 3
